type: one_to_many
key: household_heating_technology
display: radio
start: combi_boiler
options:
  -
    key: combi_boiler
    effects:
      households_heating_gas_combi_heater_share: 100
      households_heating_heat_pump_ground_share: 0
      households_heating_micro_chp_share: 0
      households_hot_water_gas_fired_heater_share: 100
      households_water_heater_heatpump_ground_water_electricity_share: 0
      households_hot_water_micro_chp_share: 0
      households_heating_heat_pump_add_on_share: 0

  -
    key: micro_chp
    effects:
      households_heating_gas_combi_heater_share: 50
      households_heating_heat_pump_ground_share: 0
      households_heating_micro_chp_share: 50
      households_hot_water_gas_fired_heater_share: 50
      households_water_heater_heatpump_ground_water_electricity_share: 0
      households_hot_water_micro_chp_share: 50
      households_heating_heat_pump_add_on_share: 0
  -
    key: heatpump_ground
    effects:
      households_heating_gas_combi_heater_share: 0
      households_heating_heat_pump_ground_share: 100
      households_heating_micro_chp_share: 0
      households_hot_water_gas_fired_heater_share: 0
      households_water_heater_heatpump_ground_water_electricity_share: 100
      households_hot_water_micro_chp_share: 0
      households_heating_heat_pump_add_on_share: 0
