type: one_to_many
key: household_lighting_type
display: radio
start: incandescent_lighting
options:
  -
    key: incandescent_lighting
    effects:
      households_lighting_incandescent_share: 100
      households_lighting_low_energy_light_bulb_share: 0
      households_lighting_light_emitting_diode_share: 0

  -
    key: fluorescent_lighting
    effects:
      households_lighting_incandescent_share: 0
      households_lighting_low_energy_light_bulb_share: 100
      households_lighting_light_emitting_diode_share: 0

  -
    key: led_lighting
    effects:
      households_lighting_incandescent_share: 0
      households_lighting_low_energy_light_bulb_share: 0
      households_lighting_light_emitting_diode_share: 100


