type: one_to_one
engine_key: households_electricity_demand_per_person
display: slider
min: -50
max: 100
step: 10.0
start: 0
unit: percentage
formula: >
  -3.5 + (number_of_appliances_in_the_house + 50) * 7.0 / 150.0