inputs:
  left:
    household_demand:
      - number_of_appliances_in_the_house
      - comfort_temperature_in_the_house
    daily_shower:
      - warm_water_demand_per_person -> daily_length_of_shower_per_person
      - warm_water_demand_per_person -> number_of_cold_showers_per_week
    insulation:
      - amount_of_insulation

  right:
    heating_technology:
      - household_heating_technology
    lighting:
      - household_lighting_type
    air_conditioning:
      - use_of_air_conditioning
    solar_panels:
      - households_market_penetration_solar_panels
      - households_heating_solar_thermal_panels_share
