development: &common
  host:                 localhost
  database:             etflex_development
  identity_map_enabled: true
  persist_in_safe_mode: true
  autocreate_indexes:   true
  include_root_in_json: true

test:
  <<: *common
  database: etflex_test

# set these environment variables on your prod server
production:
  <<: *common
  autocreate_indexes: false

  host:     'staff.mongohq.com'
  port:     '10059'
  username: 'quintel'
  password: 'qp3ofuRmtOWh7E'
  database: 'et-flex'

  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
