---
# Maps prop "behaviour" values to the name of the file in which the prop may
# be found, and the name of the constant which is exported from the file.
#
# The format is "behaviour-name: [ file_name, constant_name ]" where file_name
# is relative to Rails.root/views/props.

co2-emissions:       [ co2_emissions,              CO2EmissionsView ]
score:               [ score,                      ScoreView ]
reliability:         [ reliability,                ReliabilityView ]
costs:               [ costs,                      CostsView ]
icon:                [ icon,                       IconProp ]
renewables:          [ renewables,                 RenewablesView ]
supply-demand:       [ supply_demand,              SupplyDemandView ]

investment:          [ investment,                 InvestmentView ]
energy-bill:         [ energy_bill,                EnergyBillView ]
co2-emissions-household: [co2_emissions_household, CO2EmissionsHouseholdView ]

# Header Props.

car:                 [ headers/car,                 CarProp ]
city:                [ headers/city,                CityProp ]
eco-buildings:       [ headers/eco_buildings,       EcoBuildingsProp ]
energy-sources:      [ headers/energy_sources,      EnergySourcesProp ]
geothermal-pipeline: [ headers/geothermal_pipeline, GeothermalPipelineProp ]
ground:              [ headers/ground,              GroundProp ]
solar-heater:        [ headers/solar_heater,        SolarHeaterProp ]
turbines:            [ headers/turbines,              TurbinesProp ]

solar-thermal-panels: [ headers/solar_thermal_panels, SolarThermalPanelsProp ]
solar-panels:         [ headers/solar_panels, SolarPanelsProp ]
hot-water:            [ headers/hot_water, HotWaterProp ]
lighting:             [ headers/lighting, LightingProp ]
insulation:           [ headers/insulation, InsulationProp ]
aircon:               [ headers/aircon, AirconProp ]
